# Generated by Django 5.0.6 on 2024-08-11 09:24

import django.db.models.deletion
import million.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('fin_code', models.CharField(max_length=7, unique=True)),
                ('personal_code', models.CharField(max_length=10, unique=True)),
                ('birth_date', models.CharField(default=None, max_length=5, validators=[million.models.validate_date])),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('unit_number', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='million.user')),
            ],
        ),
        migrations.CreateModel(
            name='Utility_electric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_id', models.CharField(max_length=7, unique=True)),
                ('balance', models.FloatField()),
                ('apartment', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_utility', to='million.apartment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Utility_gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_id', models.CharField(max_length=7, unique=True)),
                ('balance', models.FloatField()),
                ('apartment', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_utility', to='million.apartment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Utility_water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_id', models.CharField(max_length=7, unique=True)),
                ('balance', models.FloatField()),
                ('apartment', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_utility', to='million.apartment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
